services:
  api:
    build: ./Api/.
    image: "precog/api:${tag}"
    container_name: Api
    ports:
      - "4001:4001"
    env_file:
      - .env

  client:
    build: ./Client/.
    image: "precog/client:${tag}"
    container_name: Client
    ports:
      - "3000:3000"
    env_file:
      - .env
  
  nginx:
    build: ./Client/nginx/.
    image: "precog/nginx:${tag}"
    container_name: nginx
    ports:   
      - "8080:80"
    env_file: 
      - .env